name: weather_forecast_repository
description: 'A Dart Repository which manages the weather forecast domain.'
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.9.2
  built_collection: ^5.1.1
  open_weather_map_api:
    path: ../open_weather_map_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  built_value_generator: ^8.9.2
  test: ^1.25.7
  mocktail: ^1.0.4

flutter:
